language: rust

sudo: required

rust:
  - 1.48.0
  - stable

matrix:
  fast_finish: true

# Using cache will block the task:
#   https://travis-ci.community/t/builds-timeout-during-or-shortly-after-creating-directory-home-travis-cache-sccache/5001
# cache:
#   cargo: true

install:
  - echo 'Installing rustfmt'
  - rustup component add rustfmt
  - echo 'Installing clippy'
  - rustup component add clippy

script:
  - cargo build --verbose --all
  - cargo fmt --all
  - cargo clippy
  - cargo test --verbose --all

notifications:
  email: false
