address = "127.0.0.1:7799"
failure_ttl = 60
failure_quorum = 1
migration_limit = 2

# The HTTP API address of other memory brokers.
replica_addresses = []
# replica_addresses = ["192.168.0.123:7799", "192.168.0.123:8899"]
# replica_addresses = "192.168.0.123:7799,192.168.0.123:8899"

# Periodically synchronize metadata to replicas.
# This is in seconds.
# Use zero to disable it.
sync_meta_interval = 10

# Set it to `true` for kubernetes StatefulSet
# to disable the chunk allocation algorithm
# and only use the index of server proxy to allocate chunks.
# If this is true，
# (1) when adding proxies, the "index" field is required and should be the index of the StatefulSet index.
# (2) failover will only change the role and will not replace proxy.
# (3) the whole undermoon cluster can only create one Redis cluster.
enable_ordered_proxy = false

storage_type = "memory"
recover_from_meta_file = true
meta_filename = "metadata"
# Refresh meta file on each update
auto_update_meta_file = true
# Periodically update meta file.
# This is in seconds.
# Use zero to disable it.
update_meta_file_interval = 10

# Use the following config to enable external http storage.
#
# This is used for external system to differentiate different undermoon clusters
# storage_type = "http"
# storage_name = "my_storage_name"
# storage_password = "somepassword"
# http_storage_address = "localhost:9999"
# refresh_interval = 30

debug = false

# Cluster Config
# Cluster config can vary between clusters.
# The config below is the default cluster config
# and could be modified dynamically in the memory broker.

# Enable string compression.
# Since commands like INCR won't work when the actual stored string
# is compressed, when string compression is enabled,
# client can only use commands like SET, GET.
#
# Could only be "disabled", "set_get_only"
compression_strategy = "disabled"
# In seconds
migration_max_migration_time = 3600
# In milliseconds
migration_max_blocking_time = 10000
# In microseconds
migration_scan_interval = 500
migration_scan_count = 16
