address = "127.0.0.1:5299"
# announce_address must be the same as the address registered in the broker.
announce_address = "127.0.0.1:5299"

slowlog_len = 1024

# In microseconds like redis.
slowlog_log_slower_than = 20000
# Execute `CONFIG SET slowlog_sample_rate 1` at runtime to record all commands.
slowlog_sample_rate = 1000

thread_number = 2

backend_conn_num = 2
# "disabled" should be good enough for most cases.
# For larger throughput with pipline enabled,
# we can try "fixed" or "dynamic" for higher throughput.
backend_batch_strategy = "disabled"
# In bytes
backend_flush_size = 1024
# In nanoseconds
backend_low_flush_interval = 200000
backend_high_flush_interval = 600000

# In millisecond. Set 0 to disable session timeout.
session_timeout = 0
# In millisecond
backend_timeout = 3000

# Password for AUTH command
# password = "yourpwd"

# Active Redirection Mode
# When active_redirection is enabled,
# all the server proxies will handle the redirection inside.
# Clients don't need to be a Redis Cluster Client.
# NOTICE: This is an experimental feature and don't use it in production.
active_redirection = false
# This is only useful when active_redirection is true.
# Use 0 to disable limitation.
# Or it should be at least 4.
max_redirections = 4

# This should almost only be used in undermoon-operator in Kubernetes.
# When scaling down, the kubernetes service may not be able to remove
# the pods already deleted from the cluster,
# which results in a `CLUSTER_NOT_FOUND` error.
# This default address will redirect the clients to the service
# and try again.
# Leave it empty to disable it.
default_redirection_address = ""

# In v1, the format of node address is just <ip:port>
# In v2, the format of node address is <ip:port@cport>,
# where `cport` is used in the gossip protocol in the official Redis Cluster.
# In undermoon, `cport` will always be 5299.
cluster_nodes_version = "v2"
