version: '3'
services:
  server_proxy1:
    container_name: server_proxy1
    image: "undermoon"
    volumes:
    - ${PWD}/examples/mem-broker/server_proxy1.toml:/undermoon/config/server_proxy.toml
    - ${PWD}/examples/run_proxy.sh:/undermoon/run_proxy.sh
    command: bash /undermoon/run_proxy.sh
    ports:
    - "6001:6001"
    - "7001:7001"
    - "7002:7002"
    environment:
    - RUST_LOG=undermoon=debug,server_proxy=debug
    - RUST_BACKTRACE=full
  server_proxy2:
    container_name: server_proxy2
    image: "undermoon"
    volumes:
    - ${PWD}/examples/mem-broker/server_proxy2.toml:/undermoon/config/server_proxy.toml
    - ${PWD}/examples/run_proxy.sh:/undermoon/run_proxy.sh
    command: bash /undermoon/run_proxy.sh
    ports:
    - "6002:6002"
    - "7003:7003"
    - "7004:7004"
    environment:
    - RUST_LOG=undermoon=debug,server_proxy=debug
    - RUST_BACKTRACE=full
  server_proxy3:
    container_name: server_proxy3
    image: "undermoon"
    volumes:
    - ${PWD}/examples/mem-broker/server_proxy3.toml:/undermoon/config/server_proxy.toml
    - ${PWD}/examples/run_proxy.sh:/undermoon/run_proxy.sh
    command: bash /undermoon/run_proxy.sh
    ports:
    - "6003:6003"
    - "7005:7005"
    - "7006:7006"
    environment:
    - RUST_LOG=undermoon=debug,server_proxy=debug
    - RUST_BACKTRACE=full

  server_proxy4:
    container_name: server_proxy4
    image: "undermoon"
    volumes:
      - ${PWD}/examples/mem-broker/server_proxy4.toml:/undermoon/config/server_proxy.toml
      - ${PWD}/examples/run_proxy.sh:/undermoon/run_proxy.sh
    command: bash /undermoon/run_proxy.sh
    ports:
      - "6004:6004"
      - "7007:7007"
      - "7008:7008"
    environment:
      - RUST_LOG=undermoon=debug,server_proxy=debug
      - RUST_BACKTRACE=full
  server_proxy5:
    container_name: server_proxy5
    image: "undermoon"
    volumes:
      - ${PWD}/examples/mem-broker/server_proxy5.toml:/undermoon/config/server_proxy.toml
      - ${PWD}/examples/run_proxy.sh:/undermoon/run_proxy.sh
    command: bash /undermoon/run_proxy.sh
    ports:
      - "6005:6005"
      - "7009:7009"
      - "7010:7010"
    environment:
      - RUST_LOG=undermoon=debug,server_proxy=debug
      - RUST_BACKTRACE=full
  server_proxy6:
    container_name: server_proxy6
    image: "undermoon"
    volumes:
      - ${PWD}/examples/mem-broker/server_proxy6.toml:/undermoon/config/server_proxy.toml
      - ${PWD}/examples/run_proxy.sh:/undermoon/run_proxy.sh
    command: bash /undermoon/run_proxy.sh
    ports:
      - "6006:6006"
      - "7011:7011"
      - "7012:7012"
    environment:
      - RUST_LOG=undermoon=debug,server_proxy=debug
      - RUST_BACKTRACE=full

  coordinator1:
    container_name: coordinator1
    image: "undermoon"
    volumes:
    - ${PWD}/examples/mem-broker/coordinator1.toml:/undermoon/config/coordinator.toml
    - ${PWD}/examples/run_coordinator.sh:/undermoon/run_coordinator.sh
    command: bash /undermoon/run_coordinator.sh
    environment:
    - RUST_LOG=undermoon=debug,coordinator=debug
    - RUST_BACKTRACE=full
    ports:
      - "8001:8001"
    depends_on:
    - "server_proxy1"
    - "server_proxy2"
    - "server_proxy3"
    - "server_proxy4"
    - "server_proxy5"
    - "server_proxy6"
    - "mem_broker"
  coordinator2:
    container_name: coordinator2
    image: "undermoon"
    volumes:
    - ${PWD}/examples/mem-broker/coordinator2.toml:/undermoon/config/coordinator.toml
    - ${PWD}/examples/run_coordinator.sh:/undermoon/run_coordinator.sh
    command: bash /undermoon/run_coordinator.sh
    environment:
    - RUST_LOG=undermoon=debug,coordinator=debug
    - RUST_BACKTRACE=full
    ports:
      - "8002:8002"
    depends_on:
    - "server_proxy1"
    - "server_proxy2"
    - "server_proxy3"
    - "server_proxy4"
    - "server_proxy5"
    - "server_proxy6"
    - "mem_broker"

  mem_broker:
    container_name: mem_broker
    image: "undermoon"
    volumes:
      - ${PWD}/examples/mem-broker/mem-broker.toml:/undermoon/config/mem-broker.toml
      - ${PWD}/examples/run_broker.sh:/undermoon/run_broker.sh
    command: bash /undermoon/run_broker.sh
    environment:
      - RUST_LOG=undermoon=debug,mem_broker=debug
      - RUST_BACKTRACE=full
    ports:
    - "7799:7799"

  redis1:
    container_name: redis1
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy1 --port 7001
    network_mode: service:server_proxy1
  redis2:
    container_name: redis2
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy1 --port 7002
    network_mode: service:server_proxy1
  redis3:
    container_name: redis3
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy2 --port 7003
    network_mode: service:server_proxy2
  redis4:
    container_name: redis4
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy2 --port 7004
    network_mode: service:server_proxy2
  redis5:
    container_name: redis5
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy3 --port 7005
    network_mode: service:server_proxy3
  redis6:
    container_name: redis6
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy3 --port 7006
    network_mode: service:server_proxy3
  redis7:
    container_name: redis7
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy4 --port 7007
    network_mode: service:server_proxy4
  redis8:
    container_name: redis8
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy4 --port 7008
    network_mode: service:server_proxy4
  redis9:
    container_name: redis9
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy5 --port 7009
    network_mode: service:server_proxy5
  redis10:
    container_name: redis10
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy5 --port 7010
    network_mode: service:server_proxy5
  redis11:
    container_name: redis11
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy6 --port 7011
    network_mode: service:server_proxy6
  redis12:
    container_name: redis12
    image: "redis"
    command: redis-server --slave-announce-ip server_proxy6 --port 7012
    network_mode: service:server_proxy6
